//! The packet modem against Direwolf's, which is the only test that counts.
//!
//! `testdata/packet/ref*.wav` were generated by Direwolf's own `gen_packets` at
//! 48 kHz — the engine's tap rate — from two known AX.25 UI frames, and
//! Direwolf's `atest` decodes all three files. They are therefore ground truth
//! written by somebody else, which is the property a loopback test can never
//! have however carefully it is written: a modem and its own demodulator agree
//! by construction, and the agreement says nothing about whether either matches
//! the deployed network.
//!
//! Regenerate with:
//!
//! ```text
//! printf 'OE3JJS>APDW12:Hello from sdroxide packet\n\
//!         OE3JJS-7>APRS,WIDE1-1:=4812.00N/01620.00E-test\n' > msgs.txt
//! gen_packets -o ref1200.wav -B 1200 -r 48000 msgs.txt   # and -B 300, -B 9600
//! ```

use sdroxide_ax25::Deframer;
use sdroxide_dsp::{AfskProfile, AfskRx};

/// The two frames in every reference file, as (source, destination, payload).
const EXPECTED: [(&str, &str, &str); 2] = [
    ("OE3JJS", "APDW12", "Hello from sdroxide packet\n"),
    ("OE3JJS-7", "APRS", "=4812.00N/01620.00E-test\n"),
];

fn wav(name: &str) -> Vec<f32> {
    let path = format!("{}/testdata/packet/{name}", env!("CARGO_MANIFEST_DIR"));
    let mut r = hound::WavReader::open(&path).unwrap_or_else(|e| panic!("opening {path}: {e}"));
    let spec = r.spec();
    assert_eq!(spec.sample_rate, 48_000, "{name} is not at the engine's tap rate");
    assert_eq!(spec.channels, 1, "{name} is not mono");
    r.samples::<i16>().map(|s| s.unwrap() as f32 / 32768.0).collect()
}

/// Pull the callsign out of a 7-byte AX.25 address field.
fn addr(bytes: &[u8]) -> String {
    let call: String =
        bytes[..6].iter().map(|&c| (c >> 1) as char).collect::<String>().trim_end().to_string();
    let ssid = (bytes[6] >> 1) & 0x0F;
    if ssid > 0 { format!("{call}-{ssid}") } else { call }
}

/// Take a decoded frame apart far enough to name it. The full codec is the
/// next stage's; this only has to prove the bits came off the air intact.
fn describe(frame: &[u8]) -> (String, String, String) {
    let dest = addr(&frame[0..7]);
    let src = addr(&frame[7..14]);
    // Skip any digipeater addresses: the low bit of byte 7 marks the last one.
    let mut i = 14;
    if frame[13] & 1 == 0 {
        while i + 7 <= frame.len() {
            let last = frame[i + 6] & 1 != 0;
            i += 7;
            if last {
                break;
            }
        }
    }
    // Control byte, then PID for a UI frame.
    let payload = if i + 2 <= frame.len() { &frame[i + 2..] } else { &[][..] };
    (src, dest, String::from_utf8_lossy(payload).to_string())
}

fn decode_afsk(name: &str, profile: AfskProfile) -> Vec<(String, String, String)> {
    let audio = wav(name);
    let mut rx = AfskRx::new(48_000.0, profile);
    let mut levels = Vec::new();
    rx.process(&audio, &mut levels);

    let mut de = Deframer::new();
    let mut frames = Vec::new();
    for lvl in levels {
        de.push_level(lvl, &mut frames);
    }
    frames.iter().map(|f| describe(f)).collect()
}

/// 1200 baud Bell 202 — the VHF workhorse, and the one an RMS Packet gateway
/// most often answers on.
#[test]
fn decodes_direwolfs_1200_baud_audio() {
    let got = decode_afsk("ref1200.wav", AfskProfile::Vhf1200);
    assert_eq!(got.len(), EXPECTED.len(), "expected 2 frames, got {got:?}");
    for (got, want) in got.iter().zip(EXPECTED) {
        assert_eq!((got.0.as_str(), got.1.as_str(), got.2.as_str()), want);
    }
}

/// 300 baud on HF, 200 Hz shift. The tones are only two thirds of a baud apart,
/// so the two matched filters are not orthogonal and the detector has less to
/// work with than at 1200 — which is exactly why it is worth pinning.
#[test]
fn decodes_direwolfs_300_baud_audio() {
    let got = decode_afsk("ref300.wav", AfskProfile::Hf300);
    assert_eq!(got.len(), EXPECTED.len(), "expected 2 frames, got {got:?}");
    for (got, want) in got.iter().zip(EXPECTED) {
        assert_eq!((got.0.as_str(), got.1.as_str(), got.2.as_str()), want);
    }
}

// ─────────────────── the other direction: our transmitter ───────────────────

/// Build a UI frame the way the reference files' sender did.
fn ui_frame(dest: &str, src: &str, payload: &[u8]) -> Vec<u8> {
    let enc = |call: &str, last: bool, hi: bool| {
        let (base, ssid) = match call.split_once('-') {
            Some((b, s)) => (b, s.parse::<u8>().unwrap()),
            None => (call, 0),
        };
        let mut v: Vec<u8> =
            base.bytes().chain(std::iter::repeat(b' ')).take(6).map(|c| c << 1).collect();
        v.push((ssid << 1) | 0b0110_0000 | u8::from(last) | if hi { 0x80 } else { 0 });
        v
    };
    let mut f = enc(dest, false, true);
    f.extend(enc(src, true, false));
    f.push(0x03); // UI
    f.push(0xF0); // no layer 3
    f.extend_from_slice(payload);
    f
}

/// Render both reference frames as our own transmission.
fn our_transmission(profile: AfskProfile) -> Vec<f32> {
    let mut fr = sdroxide_ax25::Framer::new();
    // A realistic TXDELAY: 300 ms of flags.
    fr.push_flags((0.3 * profile.baud() / 8.0).ceil() as usize);
    for (src, dest, payload) in EXPECTED {
        fr.push_frame(&ui_frame(dest, src, payload.as_bytes()));
        fr.push_flags(1);
    }
    fr.push_flags(4);
    let bits = fr.take();

    let mut tx = sdroxide_dsp::AfskTx::new(48_000.0, profile);
    tx.push_bits(&bits);
    let n = (bits.len() as f64 * 48_000.0 / profile.baud()).ceil() as usize + 4800;
    let mut audio = vec![0.0f32; n];
    tx.next_block(&mut audio);
    audio
}

/// Our transmitter must be readable by our own receiver *through the framer* —
/// frames, not raw bits, which is the level at which "did it work" is a
/// meaningful question.
fn our_tx_our_rx(profile: AfskProfile) {
    let audio = our_transmission(profile);
    let mut rx = AfskRx::new(48_000.0, profile);
    let mut levels = Vec::new();
    rx.process(&audio, &mut levels);
    let mut de = Deframer::new();
    let mut frames = Vec::new();
    for lvl in levels {
        de.push_level(lvl, &mut frames);
    }
    let got: Vec<_> = frames.iter().map(|f| describe(f)).collect();
    assert_eq!(got.len(), EXPECTED.len(), "expected 2 frames, got {got:?}");
    for (got, want) in got.iter().zip(EXPECTED) {
        assert_eq!((got.0.as_str(), got.1.as_str(), got.2.as_str()), want);
    }
}

#[test]
fn our_own_1200_baud_transmission_comes_back() {
    our_tx_our_rx(AfskProfile::Vhf1200);
}

#[test]
fn our_own_300_baud_transmission_comes_back() {
    our_tx_our_rx(AfskProfile::Hf300);
}

/// And the check that actually matters: **Direwolf** must read what we send.
///
/// Skipped rather than failed when `atest` is not installed, following
/// `wspr_corpus.rs`'s posture with the WSJT-X sample — a contributor without
/// Direwolf should not see a red build, but anyone who has it gets the real
/// answer. Install it from the AUR (`direwolf`) or build it from
/// <https://github.com/wb2osz/direwolf>.
fn atest_reads_us(profile: AfskProfile, baud: u32) {
    if std::process::Command::new("atest").arg("-h").output().is_err() {
        eprintln!("atest not installed — skipping the Direwolf check at {baud} baud");
        return;
    }
    let audio = our_transmission(profile);
    let path =
        std::env::temp_dir().join(format!("sdroxide-packet-{baud}-{}.wav", std::process::id()));
    let spec = hound::WavSpec {
        channels: 1,
        sample_rate: 48_000,
        bits_per_sample: 16,
        sample_format: hound::SampleFormat::Int,
    };
    {
        let mut w = hound::WavWriter::create(&path, spec).unwrap();
        for s in audio {
            w.write_sample((s * 20_000.0) as i16).unwrap();
        }
        w.finalize().unwrap();
    }
    let out = std::process::Command::new("atest")
        .arg("-B")
        .arg(baud.to_string())
        .arg(&path)
        .output()
        .expect("running atest");
    let _ = std::fs::remove_file(&path);
    let text = String::from_utf8_lossy(&out.stdout);
    for (src, dest, payload) in EXPECTED {
        let want = format!("{src}>{dest}");
        assert!(
            text.contains(&want),
            "Direwolf did not decode `{want}` from our {baud} baud audio.\natest said:\n{text}"
        );
        let _ = payload;
    }
}

#[test]
fn direwolf_reads_our_1200_baud_transmission() {
    atest_reads_us(AfskProfile::Vhf1200, 1200);
}

#[test]
fn direwolf_reads_our_300_baud_transmission() {
    atest_reads_us(AfskProfile::Hf300, 300);
}

// ───────────────────────────── 9600 baud G3RUH ─────────────────────────────

/// Unlike AFSK there are no tones: the scrambled bit stream *is* the modulating
/// signal, so what `gen_packets -B 9600` writes to a WAV is what a receiver
/// takes off its discriminator.
fn decode_g3ruh(name: &str) -> Vec<(String, String, String)> {
    let audio = wav(name);
    let mut rx = sdroxide_dsp::G3ruhRx::new(48_000.0);
    let mut levels = Vec::new();
    rx.process(&audio, &mut levels);

    let mut de = Deframer::new();
    let mut frames = Vec::new();
    for lvl in levels {
        de.push_level(lvl, &mut frames);
    }
    frames.iter().map(|f| describe(f)).collect()
}

#[test]
fn decodes_direwolfs_9600_baud_audio() {
    let got = decode_g3ruh("ref9600.wav");
    assert_eq!(got.len(), EXPECTED.len(), "expected 2 frames, got {got:?}");
    for (got, want) in got.iter().zip(EXPECTED) {
        assert_eq!((got.0.as_str(), got.1.as_str(), got.2.as_str()), want);
    }
}

/// Our own 9600 transmission, framed and scrambled.
fn our_g3ruh_transmission() -> Vec<f32> {
    let mut fr = sdroxide_ax25::Framer::new();
    fr.push_flags((0.3 * sdroxide_dsp::g3ruh::BAUD / 8.0).ceil() as usize);
    for (src, dest, payload) in EXPECTED {
        fr.push_frame(&ui_frame(dest, src, payload.as_bytes()));
        fr.push_flags(1);
    }
    fr.push_flags(8);
    let bits = fr.take();

    let mut tx = sdroxide_dsp::G3ruhTx::new(48_000.0);
    tx.push_bits(&bits);
    let n = (bits.len() as f64 * 48_000.0 / sdroxide_dsp::g3ruh::BAUD).ceil() as usize + 4800;
    let mut audio = vec![0.0f32; n];
    tx.next_block(&mut audio);
    audio
}

#[test]
fn our_own_9600_baud_transmission_comes_back() {
    let audio = our_g3ruh_transmission();
    let mut rx = sdroxide_dsp::G3ruhRx::new(48_000.0);
    let mut levels = Vec::new();
    rx.process(&audio, &mut levels);
    let mut de = Deframer::new();
    let mut frames = Vec::new();
    for lvl in levels {
        de.push_level(lvl, &mut frames);
    }
    let got: Vec<_> = frames.iter().map(|f| describe(f)).collect();
    assert_eq!(got.len(), EXPECTED.len(), "expected 2 frames, got {got:?}");
    for (got, want) in got.iter().zip(EXPECTED) {
        assert_eq!((got.0.as_str(), got.1.as_str(), got.2.as_str()), want);
    }
}

#[test]
fn direwolf_reads_our_9600_baud_transmission() {
    if std::process::Command::new("atest").arg("-h").output().is_err() {
        eprintln!("atest not installed — skipping the Direwolf check at 9600 baud");
        return;
    }
    let audio = our_g3ruh_transmission();
    let path =
        std::env::temp_dir().join(format!("sdroxide-packet-9600-{}.wav", std::process::id()));
    let spec = hound::WavSpec {
        channels: 1,
        sample_rate: 48_000,
        bits_per_sample: 16,
        sample_format: hound::SampleFormat::Int,
    };
    {
        let mut w = hound::WavWriter::create(&path, spec).unwrap();
        for s in audio {
            w.write_sample((s * 20_000.0) as i16).unwrap();
        }
        w.finalize().unwrap();
    }
    let out = std::process::Command::new("atest")
        .args(["-B", "9600"])
        .arg(&path)
        .output()
        .expect("running atest");
    let _ = std::fs::remove_file(&path);
    let text = String::from_utf8_lossy(&out.stdout);
    for (src, dest, _) in EXPECTED {
        let want = format!("{src}>{dest}");
        assert!(
            text.contains(&want),
            "Direwolf did not decode `{want}` from our 9600 baud audio.\natest said:\n{text}"
        );
    }
}

// ────────────── the codec, against frames Direwolf really sent ──────────────

/// Parse the reference frames with the vendored codec rather than the ad-hoc
/// `describe` above.
///
/// This is the codec's real test: the bytes came off Direwolf's own
/// transmission, through our modem and deframer, and the parse has to agree
/// about addresses, digipeater path, frame type and payload. Upstream's own
/// tests exercise it against frames upstream built.
#[test]
fn the_codec_parses_direwolfs_frames() {
    let audio = wav("ref1200.wav");
    let mut rx = AfskRx::new(48_000.0, AfskProfile::Vhf1200);
    let mut levels = Vec::new();
    rx.process(&audio, &mut levels);
    let mut de = Deframer::new();
    let mut frames = Vec::new();
    for lvl in levels {
        de.push_level(lvl, &mut frames);
    }
    assert_eq!(frames.len(), 2);

    // Both are UI frames — Direwolf's `gen_packets` sends APRS-style unproto.
    let first = sdroxide_ax25::Packet::parse(&frames[0], Some(false)).expect("parsing frame 1");
    match first.packet_type() {
        sdroxide_ax25::PacketType::Ui(ui) => {
            assert_eq!(ui.payload, b"Hello from sdroxide packet\n");
            assert_eq!(ui.pid, 0xF0, "no layer 3");
        }
        other => panic!("expected a UI frame, got {other:?}"),
    }

    // The second carries a digipeater path, which the first does not — so a
    // codec that ignored the address extension bit would pass on frame 1 and
    // mangle frame 2.
    let second = sdroxide_ax25::Packet::parse(&frames[1], Some(false)).expect("parsing frame 2");
    match second.packet_type() {
        sdroxide_ax25::PacketType::Ui(ui) => {
            assert_eq!(ui.payload, b"=4812.00N/01620.00E-test\n");
        }
        other => panic!("expected a UI frame, got {other:?}"),
    }
}

// ──────────────── through the controller, as the engine drives it ────────────────

/// The whole receive path, end to end: Direwolf's audio → `PacketController`
/// → the operator's monitor pane.
///
/// Fed in 480-sample blocks because that is what the engine hands
/// `on_rx_audio`, and a decoder that only works when it sees a whole
/// transmission at once would pass every other test in this file and decode
/// nothing on the air.
fn monitor_lines(
    file: &str,
    mode: sdroxide_types::Mode,
    baud: sdroxide_types::PacketBaud,
) -> Vec<sdroxide_types::PacketHeard> {
    let audio = wav(file);
    let cfg = sdroxide_types::DigiConfig { packet_baud: baud, ..Default::default() };
    let mut c = sdroxide_digi::PacketController::new(mode, cfg, 48_000.0);
    for block in audio.chunks(480) {
        sdroxide_digi::DigiEngine::on_rx_audio(&mut c, block);
    }
    sdroxide_digi::DigiEngine::status(&c).packet.expect("packet status").heard
}

#[test]
fn the_controller_monitors_a_1200_baud_channel() {
    let heard = monitor_lines(
        "ref1200.wav",
        sdroxide_types::Mode::Packet,
        sdroxide_types::PacketBaud::Vhf1200,
    );
    assert_eq!(heard.len(), 2, "expected two frames, got {heard:?}");
    assert_eq!(heard[0].from, "OE3JJS");
    assert_eq!(heard[0].to, "APDW12");
    assert_eq!(heard[0].kind, "UI");
    assert_eq!(heard[0].text, "Hello from sdroxide packet");
    assert!(heard[0].via.is_empty(), "the first frame is direct");

    assert_eq!(heard[1].from, "OE3JJS-7");
    assert_eq!(heard[1].via, vec!["WIDE1-1"], "the digipeater path must reach the pane");
}

#[test]
fn the_controller_monitors_a_9600_baud_channel() {
    let heard = monitor_lines(
        "ref9600.wav",
        sdroxide_types::Mode::Packet,
        sdroxide_types::PacketBaud::Vhf9600,
    );
    assert_eq!(heard.len(), 2, "expected two frames, got {heard:?}");
    assert_eq!(heard[0].text, "Hello from sdroxide packet");
}

#[test]
fn the_controller_monitors_an_hf_channel() {
    let heard = monitor_lines(
        "ref300.wav",
        sdroxide_types::Mode::PacketHf,
        sdroxide_types::PacketBaud::Hf300,
    );
    assert_eq!(heard.len(), 2, "expected two frames, got {heard:?}");
    assert_eq!(heard[0].text, "Hello from sdroxide packet");
}

/// The channel-busy flag has to follow a real transmission, or CSMA will key
/// on top of somebody. Checked against silence and against signal, because a
/// detector stuck high and one stuck low both look fine from one side.
#[test]
fn carrier_detect_follows_the_channel() {
    let cfg = sdroxide_types::DigiConfig::default();
    let mut c = sdroxide_digi::PacketController::new(sdroxide_types::Mode::Packet, cfg, 48_000.0);

    for block in vec![0.0f32; 48_000].chunks(480) {
        sdroxide_digi::DigiEngine::on_rx_audio(&mut c, block);
    }
    assert!(
        !sdroxide_digi::DigiEngine::status(&c).packet.unwrap().dcd,
        "an idle channel read as busy — CSMA would never key"
    );

    for block in wav("ref1200.wav").chunks(480) {
        sdroxide_digi::DigiEngine::on_rx_audio(&mut c, block);
    }
    assert!(
        sdroxide_digi::DigiEngine::status(&c).packet.unwrap().dcd,
        "a live channel read as idle — CSMA would key on top of the other station"
    );
}

// ─────────── the controller's own transmission, judged by Direwolf ───────────

/// Drive a beacon out of the controller exactly as the engine would, and hand
/// the audio to `atest`.
///
/// This is the first test that exercises the *whole* transmit path — beacon
/// scheduling, CSMA, TXDELAY flags, the framer, the modem, and `fill_tx_block`
/// in 480-sample blocks. A modem test cannot catch a TXDELAY that is too short
/// or a tail that truncates the closing flag; those show up here, and otherwise
/// only as a gateway that never answers.
fn controller_beacon_audio(
    baud: sdroxide_types::PacketBaud,
    mode: sdroxide_types::Mode,
) -> Vec<f32> {
    let cfg = sdroxide_types::DigiConfig {
        packet_baud: baud,
        packet_mycall: "OE3JJS-10".into(),
        packet_beacon_text: "sdroxide packet beacon".into(),
        packet_beacon_minutes: 1,
        // Persist at maximum and a short slot so the test does not wait: CSMA's
        // timing is pinned by its own unit tests, not here.
        packet_persist: 255,
        packet_slottime_ms: 1,
        ..Default::default()
    };
    let mut c = sdroxide_digi::PacketController::new(mode, cfg, 48_000.0);

    // Silence, so the channel reads clear and the slot clock runs.
    for _ in 0..20 {
        sdroxide_digi::DigiEngine::on_rx_audio(&mut c, &[0.0f32; 480]);
    }
    // Two polls a beacon interval apart: the first arms the timer, the second
    // fires it. The controller waits one interval before its first beacon.
    let t0 = std::time::SystemTime::now();
    let _ = sdroxide_digi::DigiEngine::poll(&mut c, t0, 144_800_000.0);
    for _ in 0..20 {
        sdroxide_digi::DigiEngine::on_rx_audio(&mut c, &[0.0f32; 480]);
    }
    let t1 = t0 + std::time::Duration::from_secs(61);
    let _ = sdroxide_digi::DigiEngine::poll(&mut c, t1, 144_800_000.0);

    // The beacon is now queued, but it cannot key yet: CSMA runs on the audio
    // clock, so the channel has to be observed clear for a slot first. That
    // ordering is the design — a frame queued in `poll` waits for the next
    // audio block — and driving it any other way would test a path the engine
    // never takes.
    let mut keyed = false;
    for _ in 0..40 {
        sdroxide_digi::DigiEngine::on_rx_audio(&mut c, &[0.0f32; 480]);
        let actions = sdroxide_digi::DigiEngine::poll(&mut c, t1, 144_800_000.0);
        if actions.iter().any(|a| matches!(a, sdroxide_digi::DigiAction::KeyTx)) {
            keyed = true;
            break;
        }
    }
    assert!(keyed, "the beacon never asked to key");
    assert!(sdroxide_digi::DigiEngine::tx_burst_active(&c), "keyed flag not set");

    let mut audio = Vec::new();
    let mut block = [0.0f32; 480];
    for _ in 0..4000 {
        let done = sdroxide_digi::DigiEngine::fill_tx_block(&mut c, &mut block);
        audio.extend_from_slice(&block);
        if done {
            break;
        }
    }
    assert!(!audio.is_empty(), "the over produced no audio");
    audio
}

fn atest_reads(audio: &[f32], baud: u32, want: &str) {
    if std::process::Command::new("atest").arg("-h").output().is_err() {
        eprintln!("atest not installed — skipping the Direwolf check at {baud} baud");
        return;
    }
    let path =
        std::env::temp_dir().join(format!("sdroxide-ctrl-{baud}-{}.wav", std::process::id()));
    let spec = hound::WavSpec {
        channels: 1,
        sample_rate: 48_000,
        bits_per_sample: 16,
        sample_format: hound::SampleFormat::Int,
    };
    {
        let mut w = hound::WavWriter::create(&path, spec).unwrap();
        for s in audio {
            w.write_sample((s * 20_000.0) as i16).unwrap();
        }
        w.finalize().unwrap();
    }
    let out = std::process::Command::new("atest")
        .args(["-B", &baud.to_string()])
        .arg(&path)
        .output()
        .expect("running atest");
    let _ = std::fs::remove_file(&path);
    let text = String::from_utf8_lossy(&out.stdout);
    assert!(
        text.contains(want),
        "Direwolf did not decode `{want}` from the controller's {baud} baud beacon.\natest said:\n{text}"
    );
}

#[test]
fn direwolf_reads_the_controllers_1200_baud_beacon() {
    let audio =
        controller_beacon_audio(sdroxide_types::PacketBaud::Vhf1200, sdroxide_types::Mode::Packet);
    atest_reads(&audio, 1200, "OE3JJS-10>BEACON");
}

#[test]
fn direwolf_reads_the_controllers_9600_baud_beacon() {
    let audio =
        controller_beacon_audio(sdroxide_types::PacketBaud::Vhf9600, sdroxide_types::Mode::Packet);
    atest_reads(&audio, 9600, "OE3JJS-10>BEACON");
}

#[test]
fn direwolf_reads_the_controllers_hf_beacon() {
    let audio =
        controller_beacon_audio(sdroxide_types::PacketBaud::Hf300, sdroxide_types::Mode::PacketHf);
    atest_reads(&audio, 300, "OE3JJS-10>BEACON");
}

/// Our own transmission must appear in the monitor pane, flagged as sent.
/// A beacon that goes out and never shows looks exactly like one that was
/// never sent.
#[test]
fn our_own_transmission_appears_in_the_monitor() {
    let cfg = sdroxide_types::DigiConfig {
        packet_mycall: "OE3JJS-10".into(),
        packet_beacon_text: "sdroxide packet beacon".into(),
        packet_persist: 255,
        packet_slottime_ms: 1,
        ..Default::default()
    };
    let mut c = sdroxide_digi::PacketController::new(sdroxide_types::Mode::Packet, cfg, 48_000.0);
    c.queue_beacon_now();
    for _ in 0..40 {
        sdroxide_digi::DigiEngine::on_rx_audio(&mut c, &[0.0f32; 480]);
        if sdroxide_digi::DigiEngine::poll(&mut c, std::time::SystemTime::now(), 144_800_000.0)
            .iter()
            .any(|a| matches!(a, sdroxide_digi::DigiAction::KeyTx))
        {
            break;
        }
    }
    let heard = sdroxide_digi::DigiEngine::status(&c).packet.expect("packet status").heard;
    let sent: Vec<_> = heard.iter().filter(|h| h.sent).collect();
    assert_eq!(sent.len(), 1, "our own beacon is missing from the monitor: {heard:?}");
    assert_eq!(sent[0].from, "OE3JJS-10");
    assert_eq!(sent[0].to, "BEACON");
}

// ───────────────────────── connected mode, back to back ─────────────────────

use sdroxide_ax25::{Addr, LinkConfig, PortEvent, PortRequest, port_pair};
use sdroxide_digi::{DigiAction, DigiEngine, PacketController};
use sdroxide_types::{DigiConfig, Mode, PacketBaud};

/// One station: a controller with a link port attached.
struct Station {
    ctl: PacketController,
    port: sdroxide_ax25::PortHandle,
}

fn station(call: &str) -> Station {
    let cfg = DigiConfig {
        packet_baud: PacketBaud::Vhf1200,
        packet_mycall: call.into(),
        // Key promptly: CSMA's timing is pinned by its own unit tests, and a
        // realistic slot here would make this test take minutes.
        packet_persist: 255,
        packet_slottime_ms: 1,
        packet_txdelay_ms: 60,
        packet_accept_incoming: true,
        ..Default::default()
    };
    let mut ctl = PacketController::new(Mode::Packet, cfg, 48_000.0);
    let (port, endpoint) =
        port_pair(LinkConfig { me: Addr::new(call).unwrap(), paclen: 128, maxframe: 4 });
    ctl.attach_port(endpoint);
    Station { ctl, port }
}

/// Give a station a slice of time: poll it, and if it keys, play the whole over
/// out and hand the audio back for the other station to hear.
fn step(s: &mut Station) -> Vec<f32> {
    // Enough silence for the carrier detect to fall.
    //
    // A station that has just heard a transmission still reads the channel as
    // busy — deliberately, and with a hold long enough to ride out the gap
    // between two frames of the same over. CSMA will not key until it clears,
    // so a harness that feeds one block and expects an immediate answer is
    // testing nothing but its own impatience. A real receiver has continuous
    // audio; this stands in for the quiet after the other station stops.
    let mut actions = Vec::new();
    for _ in 0..60 {
        s.ctl.on_rx_audio(&[0.0f32; 480]);
        actions = s.ctl.poll(std::time::SystemTime::now(), 144_800_000.0);
        if actions.iter().any(|a| matches!(a, DigiAction::KeyTx)) {
            break;
        }
    }
    if !actions.iter().any(|a| matches!(a, DigiAction::KeyTx)) {
        return Vec::new();
    }
    let mut audio = Vec::new();
    let mut block = [0.0f32; 480];
    for _ in 0..8000 {
        let done = s.ctl.fill_tx_block(&mut block);
        audio.extend_from_slice(&block);
        if done {
            break;
        }
    }
    s.ctl.on_burst_done();
    audio
}

/// Play one station's over into the other's receiver, in engine-sized blocks.
fn hear(s: &mut Station, audio: &[f32]) {
    for b in audio.chunks(480) {
        s.ctl.on_rx_audio(b);
    }
}

/// SABM → UA → I → RR, between two real controllers over the real modem.
///
/// Everything is exercised: the state machine, the framer, the AFSK modem, the
/// deframer, the codec, CSMA and the port bridge. The only thing standing in
/// for reality is the channel, which here is a `Vec<f32>` handed straight
/// across instead of a radio.
#[test]
fn two_stations_connect_and_exchange_data() {
    let mut a = station("OE3JJS-10");
    let mut b = station("OE3JJS-1");

    a.port
        .send(PortRequest::Connect {
            peer: Addr::new("OE3JJS-1").unwrap(),
            via: vec![],
            ext: false,
        })
        .unwrap();

    let mut connected = false;
    for _ in 0..400 {
        let from_a = step(&mut a);
        if !from_a.is_empty() {
            hear(&mut b, &from_a);
        }
        let from_b = step(&mut b);
        if !from_b.is_empty() {
            hear(&mut a, &from_b);
        }
        if let Ok(Some(PortEvent::Connected)) = a.port.recv_timeout(std::time::Duration::ZERO) {
            connected = true;
            break;
        }
    }
    assert!(connected, "the two stations never completed a SABM/UA handshake");

    // Now push data across and wait for it to be delivered at the far end.
    a.port.send(PortRequest::Data(b"hello over the air".to_vec())).unwrap();
    let mut got = Vec::new();
    for _ in 0..400 {
        let from_a = step(&mut a);
        if !from_a.is_empty() {
            hear(&mut b, &from_a);
        }
        let from_b = step(&mut b);
        if !from_b.is_empty() {
            hear(&mut a, &from_b);
        }
        while let Ok(Some(ev)) = b.port.recv_timeout(std::time::Duration::ZERO) {
            if let PortEvent::Data(d) = ev {
                got.extend(d);
            }
        }
        if !got.is_empty() {
            break;
        }
    }
    assert_eq!(
        String::from_utf8_lossy(&got),
        "hello over the air",
        "data never arrived at the far end"
    );
}
