#!/usr/bin/env python3
"""Build the packaged country-flag set for the decode list.

sdroxide ships its flags rather than fetching them, so this turns a directory
of source flag images into the small PNGs under
`crates/sdroxide-ui/assets/flags/` and regenerates the `include_bytes!` table
in `crates/sdroxide-ui/src/flags.rs`.

Which flags to build is read from the DXCC table in
`crates/sdroxide-types/src/entity_flags.rs`, so that file stays the one place
the entity → flag decision is written down.

Source images: the public-domain flag collection at
https://github.com/fonttools/region-flags (branch `gh-pages`, `png/`), whose
files are named by the same ISO codes the table uses.

    ./tools/gen_flags.py --src /path/to/region-flags/png

Run it after editing the DXCC table, and commit what it writes.
"""

import argparse
import pathlib
import re
import sys

from PIL import Image

# Flags are drawn a dozen points tall in a decode row. Storing them at three
# times that keeps them from going soft on a HiDPI screen while leaving the
# whole set small enough to sit in the wasm bundle.
MAX_W, MAX_H = 48, 32

# Flags are flat colour with antialiased edges, so a small palette costs
# nothing anyone can see at a dozen points tall and halves what the browser
# client has to download. Measured over the whole set: 254 KiB truecolour,
# 135 KiB at 64 colours, with a mean per-channel error of about 2/255.
PALETTE = 64

ROOT = pathlib.Path(__file__).resolve().parent.parent
TABLE = ROOT / "crates/sdroxide-types/src/entity_flags.rs"
OUT_DIR = ROOT / "crates/sdroxide-ui/assets/flags"
OUT_RS = ROOT / "crates/sdroxide-ui/src/flags.rs"

HEADER = '''//! The packaged country flags, and the texture cache that draws them.
//!
//! Generated by `tools/gen_flags.py` — edit the DXCC table in
//! `sdroxide-types/src/entity_flags.rs` and re-run it rather than editing the
//! list below. The images are public domain; see `assets/flags/README.md`.
//!
//! They are compiled in rather than fetched: a decode list that only shows
//! where stations are once the network answers is a decode list that shows it
//! differently on every machine, and the remote client has no business
//! reaching past sdroxide to a third-party CDN.

use std::collections::HashMap;

use eframe::egui;

/// Every flag we ship, keyed by the code [`sdroxide_types::EntityInfo::flag`]
/// carries. Sorted, so the lookup can binary-search.
static FLAG_PNG: &[(&str, &[u8])] = &[
'''

FOOTER = '''];

/// Decoded flag textures, filled the first time each flag is drawn.
///
/// One entry per *code*, not per decode: a band full of German stations
/// uploads one 48×32 texture between them. Entries stay for the life of the
/// process — the whole set decoded at once is well under a megabyte of VRAM,
/// and a band opening is exactly when re-decoding would cost the most.
#[derive(Default)]
pub struct Flags {
    /// `None` marks a code whose PNG failed to decode, so we try it once.
    cache: HashMap<&'static str, Option<egui::TextureHandle>>,
}

impl Flags {
    /// The texture for a flag code, decoding and uploading it on first use.
    fn texture(&mut self, ctx: &egui::Context, code: &str) -> Option<&egui::TextureHandle> {
        let i = FLAG_PNG.binary_search_by(|(c, _)| (*c).cmp(code)).ok()?;
        let (code, png) = FLAG_PNG[i];
        self.cache
            .entry(code)
            .or_insert_with(|| {
                let img = image::load_from_memory_with_format(png, image::ImageFormat::Png).ok()?;
                let rgba = img.to_rgba8();
                let (w, h) = rgba.dimensions();
                let ci = egui::ColorImage::from_rgba_unmultiplied(
                    [w as usize, h as usize],
                    rgba.as_raw(),
                );
                // Linear, and no mipmaps: these are drawn a shade smaller than
                // they are stored, which is the one case nearest sampling
                // turns into ragged stripes.
                Some(ctx.load_texture(format!("flag-{code}"), ci, egui::TextureOptions::LINEAR))
            })
            .as_ref()
    }

    /// Draw a flag no taller than `h` points and no wider than `1.6 * h`,
    /// keeping its own proportions, and report the box it filled.
    ///
    /// Returns `None` when there is no flag for the code — the caller decides
    /// what to put in the gap, which is usually nothing.
    pub fn show(&mut self, ui: &mut egui::Ui, code: &str, h: f32) -> Option<egui::Response> {
        let tex = self.texture(ui.ctx(), code)?;
        let [tw, th] = tex.size();
        let (tw, th) = (tw as f32, th as f32);
        // Fit inside the box rather than stretching to it: flags run from 1:1
        // (Switzerland) to 1:2 (Qatar), and a stretched one reads as wrong
        // even to somebody who could not name it.
        let scale = (h / th).min((h * 1.6) / tw);
        let size = egui::vec2(tw * scale, th * scale);
        let img = egui::Image::new((tex.id(), size)).fit_to_exact_size(size);
        Some(ui.add(img))
    }
}
'''


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--src", required=True, type=pathlib.Path,
                    help="directory of source flag PNGs named <CODE>.png")
    args = ap.parse_args()

    table = TABLE.read_text()
    codes = sorted({m for m in re.findall(r'\("[^"]+",\s*"([A-Z][A-Z0-9-]*)"\)', table)})
    if not codes:
        print(f"no flag codes found in {TABLE}", file=sys.stderr)
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for stale in OUT_DIR.glob("*.png"):
        stale.unlink()

    total = 0
    for code in codes:
        src = args.src / f"{code}.png"
        if not src.exists():
            print(f"missing source flag {src}", file=sys.stderr)
            return 1
        im = Image.open(src).convert("RGBA")
        scale = min(MAX_W / im.width, MAX_H / im.height)
        im = im.resize((max(1, round(im.width * scale)), max(1, round(im.height * scale))),
                       Image.LANCZOS)
        # FASTOCTREE is the one Pillow quantizer that keeps an alpha channel,
        # which Nepal's pennant needs and every rectangular flag ignores.
        im = im.quantize(colors=PALETTE, method=Image.FASTOCTREE)
        dst = OUT_DIR / f"{code}.png"
        im.save(dst, "PNG", optimize=True)
        total += dst.stat().st_size

    rows = "".join(
        f'    ("{c}", include_bytes!("../assets/flags/{c}.png")),\n' for c in codes
    )
    OUT_RS.write_text(HEADER + rows + FOOTER)
    print(f"{len(codes)} flags, {total / 1024:.0f} KiB -> {OUT_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
